Update 10-server-delivery.md
1. Added highlighting to line where "async" was added to the code

2. The presented code would not run, and instead would produce the error:

await db.each('SELECT id, content FROM messages WHERE id > ?',
      ^^^^^

SyntaxError: Unexpected reserved word
    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:152:18)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:299:14)
    at async link (node:internal/modules/esm/module_job:67:21)


By including the new "if (!socket.recovery) code in the "socket.on('chat message') expression, node is able to run the code without error.

The result is a program that gives bad output, but that is a separate error in the code that I have yet to debug.